name: Test Juwels Runner

on:
  push:
    branches:
      - 'main'

jobs:
  run-command:
    runs-on: [self-hosted, linux]  # adjust labels if you used custom ones
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      # - name: Run your HPC command
      #   run: |
      #     echo "Running on HPC node"
      #     hostname
      #     ml Stages/2024 Python/3.11.3
      #     cd /p/home/jusers/krochak1/juwels/cslfse/pulsar-plugin/
      #     sbatch test.sh
      - name: Submit and monitor SLURM job
        run: |
          hostname
          whoami 
          pwd

          echo "Runner user: $(whoami)"
          echo "Runner home: $HOME"
          echo "Runner path: $PATH"
          env | sort

          ls -la  /p/project1/intertwin/krochak1/pulsar-plugin/
          touch  /p/project1/intertwin/krochak1/pulsar-plugin/test_file.txt

          sbatch /p/home/jusers/krochak1/juwels/cslfse/pulsar-plugin/test.sh
