name: Test Juwels Runner

on:
  push:
    branches:
      - 'main'

jobs:
  run-command:
    runs-on: [self-hosted, linux]  # adjust labels if you used custom ones
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      # - name: Run your HPC command
      #   run: |
      #     echo "Running on HPC node"
      #     hostname
      #     ml Stages/2024 Python/3.11.3
      #     cd /p/home/jusers/krochak1/juwels/cslfse/pulsar-plugin/
      #     sbatch test.sh
      - name: Submit and monitor SLURM job
        run: |
          ###sbatch /p/project1/intertwin/krochak1/pulsar-plugin/test.sh
          
          cd /p/project1/intertwin/krochak1/pulsar-plugin/ || exit 

          echo "Submitting job..."
          JOBID=$(sbatch --parsable test.sh)
          echo "Submitted as $JOBID"

          echo "Waiting for job to complete..."
          while squeue -j "$JOBID" 2>/dev/null | grep -q "$JOBID"; do
            sleep 10
          done

          echo "Job $JOBID appears to have finished."

          echo "Querying SLURM exit code..."
          EXIT_CODE=$(sacct -j "${JOBID}.batch" --format=ExitCode -n | awk '{print $1}' | cut -d':' -f1)

          if [[ -z "$EXIT_CODE" ]]; then
            echo "ERROR: Could not retrieve exit code from sacct."
            exit 1
          fi

          if [[ "$EXIT_CODE" -ne 0 ]]; then
            echo "SLURM job failed with exit code $EXIT_CODE"
            exit 1
          else
            echo "SLURM job completed successfully with exit code 0"
          fi